sudo: required
language: bash
services:
  - docker
before_install:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
    - docker build --build-arg ARCH=armhf --no-cache -t mfilipe/pagekite:armhf .
    - docker build --build-arg ARCH=amd64 --no-cache -t mfilipe/pagekite:amd64 .
    - docker push mfilipe/pagekite
