sudo: required
language: bash
services:
  - docker
before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - for arch in ( armhf arm64 amd64 i386 ); do docker build --build-arg ARCH=${arch} --no-cache -t mfilipe/pagekite:${arch} .; done
  - docker push mfilipe/pagekite
